import "virtual:svg-icons-register";
import "../scss/style.scss";
import solutionsSlider from "./solutionsSlider";
import pressCenterSlider from "./pressCenterSlider";
import trustSlider from "./trustSlider";
import partnersSlider from "./partnersSlider";
import fancybox from "./fancybox";
import docsSlider from "./docsSlider";
import secret from "./secret";
import smoothScrolling from "./smoothScrolling";
import numbers from "./numbers";
import footer from "./footer";
import introSlider from "./introSlider";
import header from "./header";
import intro from "./intro";
import geography from "./geography";
import contacts from "./contacts";
// import balls from "./balls";
import tabs from "./tabs";
import othersSlider from "./othersSlider";
import menu from "./menu";
import newsSlider from "./newsSlider.ts";
import career from "./career.ts";
import ourTeamSlider from "./ourTeamSlider.ts";
import careerGallery from "./careerGallery.ts";
import modals from "./modals.ts";
import selects from "./selects.ts";
import fileUpload from "./fileUpload.ts";
import forms from "./forms.ts";

document.addEventListener("DOMContentLoaded", () => {
  smoothScrolling();
  fancybox();
  introSlider();
  intro();
  header();
  solutionsSlider();
  pressCenterSlider();
  trustSlider();
  partnersSlider();
  docsSlider();
  secret();
  numbers();
  footer();
  geography();
  contacts();
  // balls();
  tabs();
  othersSlider();
  menu();
  newsSlider();
  career();
  ourTeamSlider();
  careerGallery();
  modals();
  selects();
  fileUpload();
  forms();
});

window.addEventListener("load", () => {
  document.body.classList.add("loaded");
});
